[build]
  command = "next build"
  publish = ".next"
  
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Rewrites and redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Next.js Image Optimization
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 